FROM python:3.11-slim

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY constants.py .

CMD ["python3", "-m", "shiny", "run", "--host", "0.0.0.0", "--port", "8080", "--reload", "app.py"]